const siteOwnerTypeOptions = [
  { value: 1, label: "Council" },
  { value: 2, label: "Private" },
  { value: 3, label: "Sports trust" },
  { value: 4, label: "Other trust" },
  { value: 5, label: "Club" },
  { value: 6, label: "Education" },
  { value: 7, label: "Other central government agency" },
  { value: 8, label: "Don't know" },
  { value: 9, label: "Other" }
];

const siteQualityOptions = [
  { value: 1, label: "Very Good Condition" },
  { value: 2, label: "Minor Defects Only" },
  { value: 3, label: "Maintenance Required" },
  { value: 4, label: "Requires Renewal" },
  { value: 5, label: "Asset Unserviceable" }
];

const facilitySubtypeOptions = [
  { value: 1, label: 'Artificial Grass Pitch: Small sided', unit: 'Pitches (identical)'},
  { value: 2, label: 'Artificial Grass Pitch: Full size', unit: 'Pitches (identical)'},
  { value: 3, label: 'Athletics Tracks & Field: Straight track - indoor', unit: "Lanes"},
  { value: 4, label: 'Athletics Tracks & Field: Straight only - outdoor', unit: "Lanes"},
  { value: 5, label: 'Athletics Tracks & Field: Circuit - indoor', unit: "Lanes"},
  { value: 6, label: 'Athletics Tracks & Field: Circuit - outdoor', unit: "Lanes"},
  { value: 7, label: 'Athletics Tracks & Field: Long and triple jump track'},
  { value: 8, label: 'Athletics Tracks & Field: Throwing cages'},
  { value: 9, label: 'Athletics Tracks & Field: Shot put pads'},
  { value: 10, label: 'Basketball: Outdoor full size', unit: "Courts (identical)"},
  { value: 11, label: 'Basketball: Half/ mod', unit: "Courts (identical)"},
  { value: 12, label: 'Baseball: Junior', unit: "Diamonds"},
  { value: 13, label: 'Baseball: Senior', unit: "Diamonds"},
  { value: 14, label: 'Beach Volleyball: [N/A]', unit: "Courts (identical)"},
  { value: 15, label: 'Bowling Alley: [N/A]', unit: "Lanes"},
  { value: 16, label: 'Bowls: Indoor', unit: "Greens (identical)"},
  { value: 17, label: 'Bowls: Outdoor', unit: "Greens (identical)"},
  { value: 18, label: 'Boxing Club: [N/A]', unit:"m² of training area"},
  { value: 19, label: 'Climbing Centre: Climbing walls', unit:"Max wall height (m)"},
  { value: 20, label: 'Climbing Centre: Bouldering walls', unit:"Length of wall (m)"},
  { value: 21, label: 'Community hall/centre: [N/A]', unit:"m² of hall space"},
  { value: 22, label: 'Croquet court: [N/A]', unit: "Courts (identical)"},
  { value: 23, label: 'Cycling: Velodrome: indoor', unit:"Length metres"},
  { value: 24, label: 'Cycling: Velodrome/ cycling circuit: outdoor', unit:"Length metres"},
  { value: 25, label: 'Cycling: BMX', unit:"Length metres"},
  { value: 26, label: 'Cycling: Mountain bike', unit:"Length metres"},
  { value: 27, label: 'Cycling: Pump tracks', unit:"Length metres"},
  { value: 28, label: 'Cycling: Criterium circuits', unit:"Length metres"},
  { value: 29, label: 'Equestrian Centre/ Arena: Indoor', unit:"m² of performance space"},
  { value: 30, label: 'Equestrian Centre/ Arena: Outdoor', unit:"m² of performance space"},
  { value: 31, label: 'Firearms / shooting centre: Rifle range'},
  { value: 32, label: 'Firearms / shooting centre: Pistol range'},
  { value: 33, label: 'Firearms / shooting centre: Shotgun range'},
  { value: 34, label: 'Golf: Full course - 18 holes', unit: "Course length in metres (competition tees)"},
  { value: 35, label: 'Golf: Full course - 9 holes', unit: "Course length in metres (competition tees)"},
  { value: 36, label: 'Golf: Pitch and putt/ par 3', unit: "Holes"},
  { value: 37, label: 'Golf: Driving range', unit: "Covered bays"},
  { value: 38, label: 'Grass Pitches: Cricket - grass only wicket', unit: 'Pitches (identical)'},
  { value: 39, label: 'Grass Pitches: Cricket - artifical wicket only', unit: 'Pitches (identical)'},
  { value: 40, label: 'Grass Pitches: Cricket - grass and artificial wicket', unit: 'Pitches (identical)'},
  { value: 41, label: 'Grass Pitches: Cricket practice nets', unit:"Number of bowling lanes"},
  { value: 42, label: 'Grass Pitches: Full sized football (soccer)', unit: 'Pitches (identical)'},
  { value: 43, label: 'Grass Pitches: Junior football (soccer)', unit: 'Pitches (identical)'},
  { value: 44, label: 'Grass Pitches: Mini football (soccer)', unit: 'Pitches (identical)'},
  { value: 45, label: 'Grass Pitches: Senior rugby union', unit: 'Pitches (identical)'},
  { value: 46, label: 'Grass Pitches: Junior rugby union', unit: 'Pitches (identical)'},
  { value: 47, label: 'Grass Pitches: Senior rugby league', unit: 'Pitches (identical)'},
  { value: 48, label: 'Grass Pitches: Junior rugby league', unit: 'Pitches (identical)'},
  { value: 49, label: 'Grass Pitches: Full sized AFL', unit: 'Pitches (identical)'},
  { value: 50, label: 'Grass Pitches: Junior AFL', unit: 'Pitches (identical)'},
  { value: 51, label: 'Grass Pitches: Hockey', unit: 'Pitches (identical)'},
  { value: 52, label: 'Grass Pitches: Touch/ Oztag', unit: 'Pitches (identical)'},
  { value: 53, label: 'Gymnastics Centre: [N/A]', unit:"m² of space"},
  { value: 54, label: 'Health and Fitness Suite (gym): Gym floor', unit:"m² of gym equipment space", unit2: "Number of gym stations (excl free weights)"},
  { value: 55, label: 'Health and Fitness Suite (gym): Dedicated studio rooms', unit:"Number of dedicated studios", unit2: "m² of studio space", unit3: "Hours of classes per week"},
  { value: 56, label: 'Ice rinks: [N/A]', unit: "m²"},
  { value: 57, label: 'Model / radio controlled: Track'},
  { value: 58, label: 'Model / radio controlled: Aero field'},
  { value: 59, label: 'Motor sport track: Full track'},
  { value: 60, label: 'Motor sport track: Kart track'},
  { value: 61, label: 'Motor sport track: Speedway circuit'},
  { value: 62, label: 'Motor sport track: Dragway'},
  { value: 63, label: 'Motor sport track: Motorcross track'},
  { value: 64, label: 'Netball: Indoor', unit: "Courts (identical)"},
  { value: 65, label: 'Netball: Outdoor', unit: "Courts (identical)"},
  { value: 66, label: 'Pentaque: [N/A]', unit:"Number of areas"},
  { value: 67, label: 'Polo field: Polo'},
  { value: 68, label: 'Polo field: Polocrosse'},
  { value: 69, label: 'Recreation trail / course: Walking', unit:"Length metres"},
  { value: 70, label: 'Recreation trail / course: Running', unit:"Length metres"},
  { value: 71, label: 'Recreation trail / course: Cycling', unit:"Length metres"},
  { value: 72, label: 'Recreation trail / course: Multi-use', unit:"Length metres"},
  { value: 73, label: 'Reserve / informal play / play equipment (not pitches): Grass managed area', unit: "m²"},
  { value: 74, label: 'Reserve / informal play / play equipment (not pitches): Childrens play area', unit: "m²"},
  { value: 75, label: 'Rowing course: [N/A]', unit: "Length"},
  { value: 76, label: 'Sailing facility: [N/A]'},
  { value: 77, label: 'Skate park: Outdoor', unit: "m²"},
  { value: 78, label: 'Skate park: Indoor', unit: "m²"},
  { value: 79, label: 'Ski slopes: [N/A]', unit:"Length (all runs)"},
  { value: 80, label: 'Snooker/pool hall: [N/A]', unit:"Tables"},
  { value: 81, label: 'Softball: Junior', unit: "Diamonds"},
  { value: 82, label: 'Softball: Senior', unit: "Diamonds"},
  { value: 83, label: 'Sports Hall (stadia): Indoor', unit:"m² of hall space", unit2: "Number of full badminton courts (equivalent)"},
  { value: 84, label: 'Sports Hall (stadia): Outdoor', unit:"m² of hall space", unit2: "Number of full badminton courts (equivalent)"},
  { value: 85, label: 'Squash Courts: Traditional', unit: "Courts (identical)"},
  { value: 86, label: 'Squash Courts: Glass (competiton)', unit: "Courts (identical)"},
  { value: 87, label: 'Studio: [N/A]', unit:"studios"},
  { value: 88, label: 'Swimming Pool: Outdoor/leisure (all year)', unit:"m² of water space"},
  { value: 89, label: 'Swimming Pool: Indoor/leisure', unit:"m² of water space", unit2: "Length", unit3: "Hours of accumulated swim lesson sessions per week (average school term)"},
  { value: 90, label: 'Swimming Pool: Outdoor seasonal', unit:"m² of water space", unit2: "Length", unit3: "Hours of accumulated swim lesson sessions per week (average school term)"},
  { value: 91, label: 'Swimming Pool: Indoor seasonal', unit:"m² of water space", unit2: "Length", unit3: "Hours of accumulated swim lesson sessions per week (average school term)"},
  { value: 92, label: 'Swimming Pool: Indoor/ learning (program pool)', unit:"m² of water space", unit2: "Length", unit3: "Hours of accumulated swim lesson sessions per week (average school term)"},
  { value: 93, label: 'Swimming Pool: Outdoor/learning pool (program pool)', unit:"m² of water space", unit2: "Length", unit3: "Hours of accumulated swim lesson sessions per week (average school term)"},
  { value: 94, label: 'Swimming Pool: Indoor/ toddler - wet play', unit:"m² of water space", unit2: "Length", unit3: "Hours of accumulated swim lesson sessions per week (average school term)"},
  { value: 95, label: 'Swimming Pool: Outdoor/toddler - wet play', unit:"m² of water space", unit2: "Length", unit3: "Hours of accumulated swim lesson sessions per week (average school term)"},
  { value: 96, label: 'Swimming Pool: Indoor/adventure (slides etc)', unit: "Capacity of play area"},
  { value: 97, label: 'Swimming Pool: Outdoor/adventure (slides etc)', unit: "Capacity of play area"},
  { value: 98, label: 'Swimming Pool: Hydrotheraphy pool/ warm water exercise', unit:"m² of water space", unit2: "Length", unit3: "Hours of accumulated swim lesson sessions per week (average school term)"},
  { value: 99, label: 'Swimming Pool: Surf/ wave pool', unit:"m² of water space"},
  { value: 100, label: 'Swimming Pool: Diving', unit:"Number of boards", unit2: "Maximum height of boards"},
  { value: 101, label: 'Tennis Courts: Outdoor', unit: "Courts (identical)"},
  { value: 102, label: 'Tennis Courts: Indoor', unit: "Courts (identical)"},
  { value: 103, label: 'Tennis Courts: Seasonal: airhall', unit: "Courts (identical)"},
  { value: 104, label: 'Biathon / Triathlon course: [N/A]'},
  { value: 105, label: 'Waterskiing / Wakeboarding Facility: [N/A]'},
  { value: 106, label: 'Weightlifting facility (dedicated): [N/A]', unit:"m² of space"},
  { value: 107, label: 'Wrestling facility (dedicated): [N/A]', unit:"m² of space"},
  { value: 108, label: '[N/A]'}
]

const facilityTypeOptions = [
  { value: 1, label: 'Artificial Grass Pitch', subtype: facilitySubtypeOptions.slice(0,2)},
  { value: 2, label: 'Athletics Tracks & Field', subtype: facilitySubtypeOptions.slice(2,9)},
  { value: 3, label: 'Basketball', subtype: facilitySubtypeOptions.slice(9,11)},
  { value: 4, label: 'Baseball', subtype: facilitySubtypeOptions.slice(11,13)},
  { value: 5, label: 'Beach volleyball', subtype: facilitySubtypeOptions.slice(13,14)},
  { value: 6, label: 'Bowling alley', subtype: facilitySubtypeOptions.slice(14,15)},
  { value: 7, label: 'Bowls', subtype: facilitySubtypeOptions.slice(15,17)},
  { value: 8, label: 'Boxing club', subtype: facilitySubtypeOptions.slice(17,18)},
  { value: 9, label: 'Climbing Centre', subtype: facilitySubtypeOptions.slice(18,20)},
  { value: 10, label: 'Community hall / centre', subtype: facilitySubtypeOptions.slice(20,21)},
  { value: 11, label: 'Croquet court', subtype: facilitySubtypeOptions.slice(21,22)},
  { value: 12, label: 'Cycling', subtype: facilitySubtypeOptions.slice(22,28)},
  { value: 13, label: 'Equestrian Centre/ Arena', subtype: facilitySubtypeOptions.slice(28,30)},
  { value: 14, label: 'Firearms / shooting centre', subtype: facilitySubtypeOptions.slice(30,33)},
  { value: 15, label: 'Golf', subtype: facilitySubtypeOptions.slice(33,37)},
  { value: 16, label: 'Grass Pitches', subtype: facilitySubtypeOptions.slice(37,52)},
  { value: 17, label: 'Gymnastics Centre', subtype: facilitySubtypeOptions.slice(52,53)},
  { value: 18, label: 'Health and Fitness Suite (gym)', subtype: facilitySubtypeOptions.slice(53,55)},
  { value: 19, label: 'Ice Rinks', subtype: facilitySubtypeOptions.slice(55,56)},
  { value: 20, label: 'Model / radio controlled', subtype: facilitySubtypeOptions.slice(56,58)},
  { value: 21, label: 'Motor sport track', subtype: facilitySubtypeOptions.slice(58,63)},
  { value: 22, label: 'Netball', subtype: facilitySubtypeOptions.slice(63,65)},
  { value: 23, label: 'Pentaque', subtype: facilitySubtypeOptions.slice(65,66)},
  { value: 24, label: 'Polo field', subtype: facilitySubtypeOptions.slice(66,68)},
  { value: 25, label: 'Recreation trail / course', subtype: facilitySubtypeOptions.slice(68,72)},
  { value: 26, label: 'Reserve / informal play / play equipment (not pitches)', subtype: facilitySubtypeOptions.slice(72,74)},
  { value: 27, label: 'Rowing Course', subtype: facilitySubtypeOptions.slice(74,75)},
  { value: 28, label: 'Sailing facility', subtype: facilitySubtypeOptions.slice(75,76)},
  { value: 29, label: 'Skate park', subtype: facilitySubtypeOptions.slice(76,78)},
  { value: 30, label: 'Ski Slopes', subtype: facilitySubtypeOptions.slice(78,79)},
  { value: 31, label: 'Snooker / pool hall', subtype: facilitySubtypeOptions.slice(79,80)},
  { value: 32, label: 'Softball', subtype: facilitySubtypeOptions.slice(80,82)},
  { value: 33, label: 'Sports Hall (stadia)', subtype: facilitySubtypeOptions.slice(82,84)},
  { value: 34, label: 'Squash Courts', subtype: facilitySubtypeOptions.slice(84,86)},
  { value: 35, label: 'Studio', subtype: facilitySubtypeOptions.slice(86,87)},
  { value: 36, label: 'Swimming Pool', subtype: facilitySubtypeOptions.slice(87,100)},
  { value: 37, label: 'Tennis Courts', subtype: facilitySubtypeOptions.slice(100,103)},
  { value: 38, label: 'Biathon / Triathlon course', subtype: facilitySubtypeOptions.slice(103,104)},
  { value: 39, label: 'Waterskiing / Wakeboarding Facility', subtype: facilitySubtypeOptions.slice(104,105)},
  { value: 40, label: 'Weightlifting facility (dedicated)', subtype: facilitySubtypeOptions.slice(105,106)},
  { value: 41, label: 'Wrestling facility (dedicated)', subtype: facilitySubtypeOptions.slice(106,107)},
  { value: 42, label: 'Other - not listed', subtype: facilitySubtypeOptions.slice(107,108)},
]

const facilityStatusOptions = [
  { value: 1, label: "Open" },
  { value: 2, label: "New Site Planned" },
  { value: 3, label: "Under Construction" },
  { value: 4, label: "Temporarily Closed" },
  { value: 5, label: "Permanently Closed" },
  { value: 6, label: "Vacant/Available For New Operator" }
];

const csvExportDetails = [
  { name: "site_name", label: "Site Name"},
  { name: 'site_address', label: 'Site Address'},
  { name: "longitude", label: "Longitude" },
  { name: "latitude", label: "Latitude" },
  { name: "sa2_name", label: "SA2 Suburb Area"},
  { name: "lga_name", label: "Local Government Area"},
  { name: "site_build_year", label: "Approximate year of site build"},
  { name: "site_owner", label: "Operator Name"},
  { name: "site_owner_type", label: "Site ownership type", options: siteOwnerTypeOptions},
  { name: "site_quality", label: "General Site Quality", options: siteQualityOptions },
  { name: "facilityAltName", label: "Facility-specific name" },
  { name: "facility_status", label: "Facility Status", options: facilityStatusOptions},
  { name: "facility_type", label: "Facility Type", options: facilityTypeOptions},
  { name: "facility_subtype", label: "Facility Sub Type", options: facilitySubtypeOptions, facilitySubtype: 1},
  { name: "facility_type_ol1", label: "Overlapping Facility 1 Type", options: facilityTypeOptions},
  { name: "facility_subtype_ol1", label: "Overlapping Facility Sub Type", options: facilitySubtypeOptions, facilitySubtype: 2},
  { name: "facility_type_ol2", label: "Overlapping Facility 2 Type", options: facilityTypeOptions},
  { name: "facility_subtype_ol2", label: "Overlapping Facility 2 Sub Type", options: facilitySubtypeOptions, facilitySubtype: 3},
  
];

const csvExportHeaders = {
  site_name: "Site Name",
  site_address: "Site Address",
  longitude: "Longitude" ,
  latitude: "Latitude" ,
  sa2_name: "SA2 Suburb Area",
  lga_name: "Local Government Area",
  site_build_year: "Approximate year of site build",
  site_owner: "Operator Name",
  site_owner_type: "Operator Type",
  site_quality: "General Site Quality",
  facility_alt_name: "Facility Specific Name",
  facility_status: "Facility Status",
  facility_type: "Facility Type",
  facility_subtype: "Facility Sub Type",
  facility_size_value1: "Facility Size Unit#1", 
  facility_size_value2: "Facility Size Unit#2", 
  facility_size_value3: "Facility Size Unit#3",
  facility_type_ol1: "Overlapping Facility 1 Type",
  facility_subtype_ol1: "Overlapping Facility Sub Type", 
  facility_size_value1_ol1: "Overlapping Facility 1 Size Unit#1", 
  facility_size_value2_ol1: "Overlapping Facility 1 Size Unit#2", 
  facility_size_value3_ol1: "Overlapping Facility 1 Size Unit#3",
  facility_type_ol2: "Overlapping Facility 2 Type",
  facility_subtype_ol2: "Overlapping Facility 2 Sub Type", 
  facility_size_value1_ol2: "Overlapping Facility 2 Size Unit#1", 
  facility_size_value2_ol2: "Overlapping Facility 2 Size Unit#2", 
  facility_size_value3_ol2: "Overlapping Facility 2 Size Unit#3"
};

exports.csvExportDetails = csvExportDetails;
exports.csvExportHeaders = csvExportHeaders;
exports.facilityTypeOptions = facilityTypeOptions;
exports.facilitySubtypeOptions = facilitySubtypeOptions;